title: Дивошкола
description: Дивошкола — відкритий до експериментів освітній проект про корисні знання і навички. Ми прагнемо щодня дивувати й допомагати творити дива через навчання та практику.
lang: uk_UA
remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
google_analytics: 
plugins:
- jekyll-remote-theme